# Messages
#

messages:
    image: omie/messages
    ports:
        - "8000:8000"
    environment:
        - MESSAGES_SERVER_HOST=0.0.0.0
        - MESSAGES_SERVER_PORT=8000
        - MESSAGES_DB_DRIVER=sqlite3
        - MESSAGES_DB_NAME=/data/db.sqlite

    volumes:
        - ./data:/data

